apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngx-ig
  labels:
    app: ngx-ig
spec:
  ingressClassName: ngx-igk
  rules:
    - host: ngx.test
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: ngx-svc
                port:
                  number: 8666


