// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package com.xiaomi.demo.proto;

public final class BookOuterClass {
  private BookOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_book_Book_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_book_Book_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_book_BookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_book_BookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_book_BookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_book_BookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_book_BookResponse_BookMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_book_BookResponse_BookMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbook.proto\022\004book\032\036google/protobuf/wrap" +
      "pers.proto\" \n\004Book\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002" +
      " \001(\t\"S\n\013BookRequest\022\n\n\002id\030\001 \001(\003\022/\n\004name\030" +
      "\002 \001(\0132\034.google.protobuf.StringValueH\000\210\001\001" +
      "B\007\n\005_name\"\265\001\n\014BookResponse\022\031\n\005books\030\001 \003(" +
      "\0132\n.book.Book\022\034\n\006status\030\002 \001(\0162\014.book.Sta" +
      "tus\0220\n\007bookMap\030\003 \003(\0132\037.book.BookResponse" +
      ".BookMapEntry\032:\n\014BookMapEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\031\n\005value\030\002 \001(\0132\n.book.Book:\0028\001*+\n\006Sta" +
      "tus\022\013\n\007SUCCESS\020\000\022\n\n\006FAILED\020\001\022\010\n\004DEAD\020\0022\345" +
      "\001\n\013BookService\0222\n\tgetBooks1\022\021.book.BookR" +
      "equest\032\022.book.BookResponse\0224\n\tgetBooks2\022" +
      "\021.book.BookRequest\032\022.book.BookResponse0\001" +
      "\0224\n\tgetBooks3\022\021.book.BookRequest\032\022.book." +
      "BookResponse(\001\0226\n\tgetBooks4\022\021.book.BookR" +
      "equest\032\022.book.BookResponse(\0010\001B\031\n\025com.xi" +
      "aomi.demo.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_book_Book_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_book_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_book_Book_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_book_BookRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_book_BookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_book_BookRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Name", });
    internal_static_book_BookResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_book_BookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_book_BookResponse_descriptor,
        new java.lang.String[] { "Books", "Status", "BookMap", });
    internal_static_book_BookResponse_BookMapEntry_descriptor =
      internal_static_book_BookResponse_descriptor.getNestedTypes().get(0);
    internal_static_book_BookResponse_BookMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_book_BookResponse_BookMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
