// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Book.proto

package com.xiaomi.demo.proto;

public interface BookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Book books = 1;</code>
   */
  java.util.List<Book>
      getBooksList();
  /**
   * <code>repeated .Book books = 1;</code>
   */
  Book getBooks(int index);
  /**
   * <code>repeated .Book books = 1;</code>
   */
  int getBooksCount();
  /**
   * <code>repeated .Book books = 1;</code>
   */
  java.util.List<? extends BookOrBuilder>
      getBooksOrBuilderList();
  /**
   * <code>repeated .Book books = 1;</code>
   */
  BookOrBuilder getBooksOrBuilder(
          int index);

  /**
   * <code>.Status status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.Status status = 2;</code>
   * @return The status.
   */
  Status getStatus();

  /**
   * <code>map&lt;string, .Book&gt; bookMap = 3;</code>
   */
  int getBookMapCount();
  /**
   * <code>map&lt;string, .Book&gt; bookMap = 3;</code>
   */
  boolean containsBookMap(
          String key);
  /**
   * Use {@link #getBookMapMap()} instead.
   */
  @Deprecated
  java.util.Map<String, Book>
  getBookMap();
  /**
   * <code>map&lt;string, .Book&gt; bookMap = 3;</code>
   */
  java.util.Map<String, Book>
  getBookMapMap();
  /**
   * <code>map&lt;string, .Book&gt; bookMap = 3;</code>
   */

  Book getBookMapOrDefault(
          String key,
          Book defaultValue);
  /**
   * <code>map&lt;string, .Book&gt; bookMap = 3;</code>
   */

  Book getBookMapOrThrow(
          String key);
}
