// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package com.xiaomi.demo.proto;

public interface BookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:book.BookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .book.Book books = 1;</code>
   */
  java.util.List<com.xiaomi.demo.proto.Book> 
      getBooksList();
  /**
   * <code>repeated .book.Book books = 1;</code>
   */
  com.xiaomi.demo.proto.Book getBooks(int index);
  /**
   * <code>repeated .book.Book books = 1;</code>
   */
  int getBooksCount();
  /**
   * <code>repeated .book.Book books = 1;</code>
   */
  java.util.List<? extends com.xiaomi.demo.proto.BookOrBuilder> 
      getBooksOrBuilderList();
  /**
   * <code>repeated .book.Book books = 1;</code>
   */
  com.xiaomi.demo.proto.BookOrBuilder getBooksOrBuilder(
      int index);

  /**
   * <code>.book.Status status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.book.Status status = 2;</code>
   * @return The status.
   */
  com.xiaomi.demo.proto.Status getStatus();

  /**
   * <code>map&lt;string, .book.Book&gt; bookMap = 3;</code>
   */
  int getBookMapCount();
  /**
   * <code>map&lt;string, .book.Book&gt; bookMap = 3;</code>
   */
  boolean containsBookMap(
      java.lang.String key);
  /**
   * Use {@link #getBookMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.xiaomi.demo.proto.Book>
  getBookMap();
  /**
   * <code>map&lt;string, .book.Book&gt; bookMap = 3;</code>
   */
  java.util.Map<java.lang.String, com.xiaomi.demo.proto.Book>
  getBookMapMap();
  /**
   * <code>map&lt;string, .book.Book&gt; bookMap = 3;</code>
   */

  com.xiaomi.demo.proto.Book getBookMapOrDefault(
      java.lang.String key,
      com.xiaomi.demo.proto.Book defaultValue);
  /**
   * <code>map&lt;string, .book.Book&gt; bookMap = 3;</code>
   */

  com.xiaomi.demo.proto.Book getBookMapOrThrow(
      java.lang.String key);
}
