// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package com.xiaomi.demo.proto;

public interface BookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:book.BookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   * @return The name.
   */
  com.google.protobuf.StringValue getName();
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getNameOrBuilder();
}
