// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package com.xiaomi.demo.proto;

public interface BookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:book.Book)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
