// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Book.proto

package com.xiaomi.demo.proto;

public interface BookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 bookId = 1;</code>
   * @return The bookId.
   */
  long getBookId();

  /**
   * <code>.google.protobuf.StringValue bookName = 2;</code>
   * @return Whether the bookName field is set.
   */
  boolean hasBookName();
  /**
   * <code>.google.protobuf.StringValue bookName = 2;</code>
   * @return The bookName.
   */
  com.google.protobuf.StringValue getBookName();
  /**
   * <code>.google.protobuf.StringValue bookName = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getBookNameOrBuilder();
}
