apiVersion: v1
kind: Pod
metadata:
  name: pod-env
  labels:
    app: pod-env
    owner: chrono
    env: demo
    region: north
    tier: back
spec:
  containers:
  - name: pod-env
    image: busybox
    imagePullPolicy: IfNotPresent
    env:
      - name: os
        value: "ubuntu"
      - name: debug
        value: "hello world"
    command:
      - /bin/echo
    args:
      - "$(os), $(debug)"
