apiVersion: v1
kind: Pod
metadata:
  name: busy-box
  labels:
    app: pod-env
    owner: chrono
    env: demo
    region: north
    tier: back
spec:
  containers:
  - name: pod-env
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    env:
      - name: os
        value: "ubuntu"
      - name: debug
        value: "hello world"
    command:
      - /bin/echo
    args:
      - "$(os), $(debug)"
    lifecycle:
      postStart:
        exec:
          command: [ "/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message" ]
#      preStop:
#        exec:
#          command: [ "/usr/sbin/nginx","-s","quit" ]
