apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: example
spec:
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: db
  namespace: example
subsets:
  - addresses:
      - ip: 10.244.0.1
      - ip: 10.244.0.2
      - ip: 10.244.0.3
    ports:
    - port: 3306
      protocol: TCP