apiVersion: v1
# 一个代理层，向外暴露端口
kind: Service
metadata:
  name: ngx-svc
  labels:
    app: ngx-svc
# 对象名字.空间.svc.cluster.local  例如 ngx-svc.default.svc.cluster.local
spec:
  selector:
    app: nginx-dep
  ports:
    # 向外暴露的端口
    - port: 8081
      # pod暴露的端口
      targetPort: 80
  # 向外暴露端口
  # ExternalName 转换到其他的一个内部域名上
  # LoadBalancer, 绑定一个loadBalance
  # NodePort, 绑定宿主机的一个端口
  # ClusterIp(默认值) 提供一个虚拟ip
  type: NodePort


