// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Book.proto

package com.xiaomi.demo.data;

public interface BookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xiaomi.demo.data.Book)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated int32 scores = 3;</code>
   */
  java.util.List<java.lang.Integer> getScoresList();
  /**
   * <code>repeated int32 scores = 3;</code>
   */
  int getScoresCount();
  /**
   * <code>repeated int32 scores = 3;</code>
   */
  int getScores(int index);
}
