// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/People.proto

package com.xiaomi.demo.data;

public interface PoepleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xiaomi.demo.data.Poeple)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
