// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Book.proto

package com.xiaomi.demo.proto;

public interface BookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Book books = 1;</code>
   */
  java.util.List<Book>
      getBooksList();
  /**
   * <code>repeated .Book books = 1;</code>
   */
  Book getBooks(int index);
  /**
   * <code>repeated .Book books = 1;</code>
   */
  int getBooksCount();
  /**
   * <code>repeated .Book books = 1;</code>
   */
  java.util.List<? extends BookOrBuilder>
      getBooksOrBuilderList();
  /**
   * <code>repeated .Book books = 1;</code>
   */
  BookOrBuilder getBooksOrBuilder(
          int index);

  /**
   * <code>.Status status = 2;</code>
   */
  int getStatusValue();
  /**
   * <code>.Status status = 2;</code>
   */
  Status getStatus();
}
