// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Book1.proto

package com.xiaomi.demo.proto;

public final class Book1 {
  private Book1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiaomi_demo_BookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xiaomi_demo_BookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiaomi_demo_BookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xiaomi_demo_BookResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/Book1.proto\022\017com.xiaomi.demo\"\'\n\013" +
      "BookRequest\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\003\"h\n" +
      "\014BookResponse\022\020\n\010bookName\030\001 \001(\t\022\n\n\002id\030\002 " +
      "\001(\003\022(\n\004code\030\003 \001(\0162\032.com.xiaomi.demo.Erro" +
      "rCode\022\020\n\010errorMsg\030\004 \001(\t*8\n\tErrorCode\022\r\n\t" +
      "NOT_FOUND\020\000\022\017\n\013INTER_ERROR\020\001\022\013\n\007SUCCESS\020" +
      "\0022W\n\013BookService\022H\n\007getBook\022\034.com.xiaomi" +
      ".demo.BookRequest\032\035.com.xiaomi.demo.Book" +
      "Response\"\000B\034\n\025com.xiaomi.demo.protoP\001\210\001\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xiaomi_demo_BookRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xiaomi_demo_BookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xiaomi_demo_BookRequest_descriptor,
        new java.lang.String[] { "Name", "Id", });
    internal_static_com_xiaomi_demo_BookResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xiaomi_demo_BookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xiaomi_demo_BookResponse_descriptor,
        new java.lang.String[] { "BookName", "Id", "Code", "ErrorMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
