// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Book.proto

package com.xiaomi.demo.proto;

/**
 * Protobuf type {@code BookResponse}
 */
public  final class BookResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BookResponse)
    BookResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BookResponse.newBuilder() to construct.
  private BookResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BookResponse() {
    books_ = java.util.Collections.emptyList();
    status_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BookResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              books_ = new java.util.ArrayList<Book>();
              mutable_bitField0_ |= 0x00000001;
            }
            books_.add(
                input.readMessage(Book.parser(), extensionRegistry));
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        books_ = java.util.Collections.unmodifiableList(books_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BookOuterClass.internal_static_BookResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BookOuterClass.internal_static_BookResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BookResponse.class, BookResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BOOKS_FIELD_NUMBER = 1;
  private java.util.List<Book> books_;
  /**
   * <code>repeated .Book books = 1;</code>
   */
  public java.util.List<Book> getBooksList() {
    return books_;
  }
  /**
   * <code>repeated .Book books = 1;</code>
   */
  public java.util.List<? extends BookOrBuilder>
      getBooksOrBuilderList() {
    return books_;
  }
  /**
   * <code>repeated .Book books = 1;</code>
   */
  public int getBooksCount() {
    return books_.size();
  }
  /**
   * <code>repeated .Book books = 1;</code>
   */
  public Book getBooks(int index) {
    return books_.get(index);
  }
  /**
   * <code>repeated .Book books = 1;</code>
   */
  public BookOrBuilder getBooksOrBuilder(
      int index) {
    return books_.get(index);
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <code>.Status status = 2;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.Status status = 2;</code>
   */
  public Status getStatus() {
    @SuppressWarnings("deprecation")
    Status result = Status.valueOf(status_);
    return result == null ? Status.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < books_.size(); i++) {
      output.writeMessage(1, books_.get(i));
    }
    if (status_ != Status.SUCCESS.getNumber()) {
      output.writeEnum(2, status_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < books_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, books_.get(i));
    }
    if (status_ != Status.SUCCESS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BookResponse)) {
      return super.equals(obj);
    }
    BookResponse other = (BookResponse) obj;

    boolean result = true;
    result = result && getBooksList()
        .equals(other.getBooksList());
    result = result && status_ == other.status_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBooksCount() > 0) {
      hash = (37 * hash) + BOOKS_FIELD_NUMBER;
      hash = (53 * hash) + getBooksList().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BookResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BookResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BookResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BookResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BookResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BookResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BookResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BookResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static BookResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static BookResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BookResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BookResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BookResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BookResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BookResponse)
      BookResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BookOuterClass.internal_static_BookResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BookOuterClass.internal_static_BookResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BookResponse.class, BookResponse.Builder.class);
    }

    // Construct using com.xiaomi.demo.proto.BookResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBooksFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (booksBuilder_ == null) {
        books_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        booksBuilder_.clear();
      }
      status_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BookOuterClass.internal_static_BookResponse_descriptor;
    }

    @Override
    public BookResponse getDefaultInstanceForType() {
      return BookResponse.getDefaultInstance();
    }

    @Override
    public BookResponse build() {
      BookResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public BookResponse buildPartial() {
      BookResponse result = new BookResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (booksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          books_ = java.util.Collections.unmodifiableList(books_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.books_ = books_;
      } else {
        result.books_ = booksBuilder_.build();
      }
      result.status_ = status_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BookResponse) {
        return mergeFrom((BookResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BookResponse other) {
      if (other == BookResponse.getDefaultInstance()) return this;
      if (booksBuilder_ == null) {
        if (!other.books_.isEmpty()) {
          if (books_.isEmpty()) {
            books_ = other.books_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBooksIsMutable();
            books_.addAll(other.books_);
          }
          onChanged();
        }
      } else {
        if (!other.books_.isEmpty()) {
          if (booksBuilder_.isEmpty()) {
            booksBuilder_.dispose();
            booksBuilder_ = null;
            books_ = other.books_;
            bitField0_ = (bitField0_ & ~0x00000001);
            booksBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBooksFieldBuilder() : null;
          } else {
            booksBuilder_.addAllMessages(other.books_);
          }
        }
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      BookResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (BookResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<Book> books_ =
      java.util.Collections.emptyList();
    private void ensureBooksIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        books_ = new java.util.ArrayList<Book>(books_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Book, Book.Builder, BookOrBuilder> booksBuilder_;

    /**
     * <code>repeated .Book books = 1;</code>
     */
    public java.util.List<Book> getBooksList() {
      if (booksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(books_);
      } else {
        return booksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public int getBooksCount() {
      if (booksBuilder_ == null) {
        return books_.size();
      } else {
        return booksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Book getBooks(int index) {
      if (booksBuilder_ == null) {
        return books_.get(index);
      } else {
        return booksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Builder setBooks(
        int index, Book value) {
      if (booksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBooksIsMutable();
        books_.set(index, value);
        onChanged();
      } else {
        booksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Builder setBooks(
        int index, Book.Builder builderForValue) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        books_.set(index, builderForValue.build());
        onChanged();
      } else {
        booksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Builder addBooks(Book value) {
      if (booksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBooksIsMutable();
        books_.add(value);
        onChanged();
      } else {
        booksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Builder addBooks(
        int index, Book value) {
      if (booksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBooksIsMutable();
        books_.add(index, value);
        onChanged();
      } else {
        booksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Builder addBooks(
        Book.Builder builderForValue) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        books_.add(builderForValue.build());
        onChanged();
      } else {
        booksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Builder addBooks(
        int index, Book.Builder builderForValue) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        books_.add(index, builderForValue.build());
        onChanged();
      } else {
        booksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Builder addAllBooks(
        Iterable<? extends Book> values) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, books_);
        onChanged();
      } else {
        booksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Builder clearBooks() {
      if (booksBuilder_ == null) {
        books_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        booksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Builder removeBooks(int index) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        books_.remove(index);
        onChanged();
      } else {
        booksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Book.Builder getBooksBuilder(
        int index) {
      return getBooksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public BookOrBuilder getBooksOrBuilder(
        int index) {
      if (booksBuilder_ == null) {
        return books_.get(index);  } else {
        return booksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public java.util.List<? extends BookOrBuilder>
         getBooksOrBuilderList() {
      if (booksBuilder_ != null) {
        return booksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(books_);
      }
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Book.Builder addBooksBuilder() {
      return getBooksFieldBuilder().addBuilder(
          Book.getDefaultInstance());
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public Book.Builder addBooksBuilder(
        int index) {
      return getBooksFieldBuilder().addBuilder(
          index, Book.getDefaultInstance());
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    public java.util.List<Book.Builder>
         getBooksBuilderList() {
      return getBooksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Book, Book.Builder, BookOrBuilder>
        getBooksFieldBuilder() {
      if (booksBuilder_ == null) {
        booksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Book, Book.Builder, BookOrBuilder>(
                books_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        books_ = null;
      }
      return booksBuilder_;
    }

    private int status_ = 0;
    /**
     * <code>.Status status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.Status status = 2;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Status status = 2;</code>
     */
    public Status getStatus() {
      @SuppressWarnings("deprecation")
      Status result = Status.valueOf(status_);
      return result == null ? Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.Status status = 2;</code>
     */
    public Builder setStatus(Status value) {
      if (value == null) {
        throw new NullPointerException();
      }

      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Status status = 2;</code>
     */
    public Builder clearStatus() {

      status_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BookResponse)
  }

  // @@protoc_insertion_point(class_scope:BookResponse)
  private static final BookResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BookResponse();
  }

  public static BookResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BookResponse>
      PARSER = new com.google.protobuf.AbstractParser<BookResponse>() {
    @Override
    public BookResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BookResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BookResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BookResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public BookResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

