// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Book1.proto

package com.xiaomi.demo.proto;

public interface BookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xiaomi.demo.BookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 id = 2;</code>
   */
  long getId();
}
