// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Book.proto

package com.xiaomi.demo.proto;

public interface BookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 bookId = 1;</code>
   */
  long getBookId();
}
