// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Book.proto

package com.xiaomi.demo.proto;

public interface BookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Book)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 bookId = 1;</code>
   */
  long getBookId();

  /**
   * <code>string bookName = 2;</code>
   */
  String getBookName();
  /**
   * <code>string bookName = 2;</code>
   */
  com.google.protobuf.ByteString
      getBookNameBytes();
}
