// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Book1.proto

package com.xiaomi.demo.proto;

/**
 * Protobuf type {@code com.xiaomi.demo.BookResponse}
 */
public  final class BookResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xiaomi.demo.BookResponse)
    BookResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BookResponse.newBuilder() to construct.
  private BookResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BookResponse() {
    bookName_ = "";
    id_ = 0L;
    code_ = 0;
    errorMsg_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BookResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            bookName_ = s;
            break;
          }
          case 16: {

            id_ = input.readInt64();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            code_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            errorMsg_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xiaomi.demo.proto.Book1.internal_static_com_xiaomi_demo_BookResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xiaomi.demo.proto.Book1.internal_static_com_xiaomi_demo_BookResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xiaomi.demo.proto.BookResponse.class, com.xiaomi.demo.proto.BookResponse.Builder.class);
  }

  public static final int BOOKNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object bookName_;
  /**
   * <code>string bookName = 1;</code>
   */
  public java.lang.String getBookName() {
    java.lang.Object ref = bookName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bookName_ = s;
      return s;
    }
  }
  /**
   * <code>string bookName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBookNameBytes() {
    java.lang.Object ref = bookName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bookName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private long id_;
  /**
   * <code>int64 id = 2;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int CODE_FIELD_NUMBER = 3;
  private int code_;
  /**
   * <code>.com.xiaomi.demo.ErrorCode code = 3;</code>
   */
  public int getCodeValue() {
    return code_;
  }
  /**
   * <code>.com.xiaomi.demo.ErrorCode code = 3;</code>
   */
  public com.xiaomi.demo.proto.ErrorCode getCode() {
    @SuppressWarnings("deprecation")
    com.xiaomi.demo.proto.ErrorCode result = com.xiaomi.demo.proto.ErrorCode.valueOf(code_);
    return result == null ? com.xiaomi.demo.proto.ErrorCode.UNRECOGNIZED : result;
  }

  public static final int ERRORMSG_FIELD_NUMBER = 4;
  private volatile java.lang.Object errorMsg_;
  /**
   * <code>string errorMsg = 4;</code>
   */
  public java.lang.String getErrorMsg() {
    java.lang.Object ref = errorMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string errorMsg = 4;</code>
   */
  public com.google.protobuf.ByteString
      getErrorMsgBytes() {
    java.lang.Object ref = errorMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBookNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bookName_);
    }
    if (id_ != 0L) {
      output.writeInt64(2, id_);
    }
    if (code_ != com.xiaomi.demo.proto.ErrorCode.NOT_FOUND.getNumber()) {
      output.writeEnum(3, code_);
    }
    if (!getErrorMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, errorMsg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBookNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bookName_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, id_);
    }
    if (code_ != com.xiaomi.demo.proto.ErrorCode.NOT_FOUND.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, code_);
    }
    if (!getErrorMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, errorMsg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xiaomi.demo.proto.BookResponse)) {
      return super.equals(obj);
    }
    com.xiaomi.demo.proto.BookResponse other = (com.xiaomi.demo.proto.BookResponse) obj;

    boolean result = true;
    result = result && getBookName()
        .equals(other.getBookName());
    result = result && (getId()
        == other.getId());
    result = result && code_ == other.code_;
    result = result && getErrorMsg()
        .equals(other.getErrorMsg());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOOKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBookName().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + code_;
    hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMsg().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xiaomi.demo.proto.BookResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xiaomi.demo.proto.BookResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xiaomi.demo.proto.BookResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xiaomi.demo.proto.BookResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xiaomi.demo.proto.BookResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xiaomi.demo.proto.BookResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xiaomi.demo.proto.BookResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xiaomi.demo.proto.BookResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xiaomi.demo.proto.BookResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xiaomi.demo.proto.BookResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xiaomi.demo.proto.BookResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xiaomi.demo.proto.BookResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xiaomi.demo.proto.BookResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.xiaomi.demo.BookResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xiaomi.demo.BookResponse)
      com.xiaomi.demo.proto.BookResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiaomi.demo.proto.Book1.internal_static_com_xiaomi_demo_BookResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiaomi.demo.proto.Book1.internal_static_com_xiaomi_demo_BookResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiaomi.demo.proto.BookResponse.class, com.xiaomi.demo.proto.BookResponse.Builder.class);
    }

    // Construct using com.xiaomi.demo.proto.BookResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bookName_ = "";

      id_ = 0L;

      code_ = 0;

      errorMsg_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xiaomi.demo.proto.Book1.internal_static_com_xiaomi_demo_BookResponse_descriptor;
    }

    @java.lang.Override
    public com.xiaomi.demo.proto.BookResponse getDefaultInstanceForType() {
      return com.xiaomi.demo.proto.BookResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.xiaomi.demo.proto.BookResponse build() {
      com.xiaomi.demo.proto.BookResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xiaomi.demo.proto.BookResponse buildPartial() {
      com.xiaomi.demo.proto.BookResponse result = new com.xiaomi.demo.proto.BookResponse(this);
      result.bookName_ = bookName_;
      result.id_ = id_;
      result.code_ = code_;
      result.errorMsg_ = errorMsg_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xiaomi.demo.proto.BookResponse) {
        return mergeFrom((com.xiaomi.demo.proto.BookResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xiaomi.demo.proto.BookResponse other) {
      if (other == com.xiaomi.demo.proto.BookResponse.getDefaultInstance()) return this;
      if (!other.getBookName().isEmpty()) {
        bookName_ = other.bookName_;
        onChanged();
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.code_ != 0) {
        setCodeValue(other.getCodeValue());
      }
      if (!other.getErrorMsg().isEmpty()) {
        errorMsg_ = other.errorMsg_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xiaomi.demo.proto.BookResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xiaomi.demo.proto.BookResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object bookName_ = "";
    /**
     * <code>string bookName = 1;</code>
     */
    public java.lang.String getBookName() {
      java.lang.Object ref = bookName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bookName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bookName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBookNameBytes() {
      java.lang.Object ref = bookName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bookName = 1;</code>
     */
    public Builder setBookName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bookName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bookName = 1;</code>
     */
    public Builder clearBookName() {
      
      bookName_ = getDefaultInstance().getBookName();
      onChanged();
      return this;
    }
    /**
     * <code>string bookName = 1;</code>
     */
    public Builder setBookNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bookName_ = value;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 2;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 2;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private int code_ = 0;
    /**
     * <code>.com.xiaomi.demo.ErrorCode code = 3;</code>
     */
    public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.com.xiaomi.demo.ErrorCode code = 3;</code>
     */
    public Builder setCodeValue(int value) {
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.xiaomi.demo.ErrorCode code = 3;</code>
     */
    public com.xiaomi.demo.proto.ErrorCode getCode() {
      @SuppressWarnings("deprecation")
      com.xiaomi.demo.proto.ErrorCode result = com.xiaomi.demo.proto.ErrorCode.valueOf(code_);
      return result == null ? com.xiaomi.demo.proto.ErrorCode.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.xiaomi.demo.ErrorCode code = 3;</code>
     */
    public Builder setCode(com.xiaomi.demo.proto.ErrorCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      code_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.xiaomi.demo.ErrorCode code = 3;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errorMsg_ = "";
    /**
     * <code>string errorMsg = 4;</code>
     */
    public java.lang.String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string errorMsg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errorMsg = 4;</code>
     */
    public Builder setErrorMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string errorMsg = 4;</code>
     */
    public Builder clearErrorMsg() {
      
      errorMsg_ = getDefaultInstance().getErrorMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string errorMsg = 4;</code>
     */
    public Builder setErrorMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMsg_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xiaomi.demo.BookResponse)
  }

  // @@protoc_insertion_point(class_scope:com.xiaomi.demo.BookResponse)
  private static final com.xiaomi.demo.proto.BookResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xiaomi.demo.proto.BookResponse();
  }

  public static com.xiaomi.demo.proto.BookResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BookResponse>
      PARSER = new com.google.protobuf.AbstractParser<BookResponse>() {
    @java.lang.Override
    public BookResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BookResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BookResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BookResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xiaomi.demo.proto.BookResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

