// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Book1.proto

package com.xiaomi.demo.proto;

/**
 * Protobuf enum {@code com.xiaomi.demo.ErrorCode}
 */
public enum ErrorCode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NOT_FOUND = 0;</code>
   */
  NOT_FOUND(0),
  /**
   * <code>INTER_ERROR = 1;</code>
   */
  INTER_ERROR(1),
  /**
   * <code>SUCCESS = 2;</code>
   */
  SUCCESS(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NOT_FOUND = 0;</code>
   */
  public static final int NOT_FOUND_VALUE = 0;
  /**
   * <code>INTER_ERROR = 1;</code>
   */
  public static final int INTER_ERROR_VALUE = 1;
  /**
   * <code>SUCCESS = 2;</code>
   */
  public static final int SUCCESS_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ErrorCode valueOf(int value) {
    return forNumber(value);
  }

  public static ErrorCode forNumber(int value) {
    switch (value) {
      case 0: return NOT_FOUND;
      case 1: return INTER_ERROR;
      case 2: return SUCCESS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ErrorCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
          public ErrorCode findValueByNumber(int number) {
            return ErrorCode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.xiaomi.demo.proto.Book1.getDescriptor().getEnumTypes().get(0);
  }

  private static final ErrorCode[] VALUES = values();

  public static ErrorCode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.xiaomi.demo.ErrorCode)
}

