nacos:
  config:
    server-addr: "localhost:8848"
    namespace: "f93a57f1-4416-4db6-a4ff-6a71ecdde69d"
    group: "demo"
    data-id: "application-dev"
    auto-refresh: true
dubbo:
  registry:
    address: "nacos://localhost:8848?username=nacos&password=nacos"
  application:
    name: "demo"
    logger: "slf4j"
    register-mode: instance
  protocol:
    name: "dubbo"
    port: -1
  scan:
    base-packages: "com.xiaomi.demo.rpc.dubbo"

