nacos:
  config:
    server-addr: "localhost:8848"
    namespace: "f93a57f1-4416-4db6-a4ff-6a71ecdde69d"
    group: "demo"
    data-id: "application-dev"
    auto-refresh: true
    bootstrap:
      enable: true
  discovery:
    server-addr: "localhost:8848"
    namespace: "f93a57f1-4416-4db6-a4ff-6a71ecdde69d"
    username: "nacos"
    password: "nacos"
    auto-register: true
    register:
      enabled: true
dubbo:
  registry:
    address: "nacos://127.0.0.1:8848"
  application:
    name: "demo"
    logger: "slf4j"
  protocol:
    name: "dubbo"
    port: -1
  scan:
    base-packages: "com.xiaomi.demo.rpc.dubbo"

