@startuml
|使用前|
start
:用户打开旅游App;
|#LightSkyBlue|使用后|
:用户浏览旅游信息;
|#AntiqueWhite|登机前|
:用户办理登机手续;
:系统生成登机牌;
|使用前|
:用户到达机场;
|登机前|
:用户通过安检;
|#LightCoral|乘机中|
:用户登机;
:飞机起飞;
:用户享受飞行服务;
|#PaleGreen|登机后|
:飞机降落;
:用户下飞机;
:用户离开机场;
stop
@enduml
