@startuml
'https://plantuml.com/sequence-diagram

前端->后端服务器:1.1 创建业务表单(表单名，关联的数据模型等)
后端服务器->数据库:1.2 创建相关表单记录
数据库->后端服务器:1.3 创建成功
后端服务器->前端:1.4 返回结果


前端->后端服务器:2.1 创建业务表单详情(表单布局(json)，表单关联数据格式(Json)等)
后端服务器->数据库:2.2 创建业务表单详情记录
数据库->后端服务器:2.3 创建成功
后端服务器->前端:2.4 返回结果
@enduml