// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Book.proto

package com.xiaomi.demo.rpc.proto;

public final class BookOuterClass {
  private BookOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Book_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Book_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookResponse_BookMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookResponse_BookMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nBook.proto\032\036google/protobuf/wrappers.p" +
      "roto\"(\n\004Book\022\016\n\006bookId\030\001 \001(\003\022\020\n\010bookName" +
      "\030\002 \001(\t\"_\n\013BookRequest\022\016\n\006bookId\030\001 \001(\003\0223\n" +
      "\010bookName\030\002 \001(\0132\034.google.protobuf.String" +
      "ValueH\000\210\001\001B\013\n\t_bookName\"\241\001\n\014BookResponse" +
      "\022\024\n\005books\030\001 \003(\0132\005.Book\022\027\n\006status\030\002 \001(\0162\007" +
      ".Status\022+\n\007bookMap\030\003 \003(\0132\032.BookResponse." +
      "BookMapEntry\0325\n\014BookMapEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\024\n\005value\030\002 \001(\0132\005.Book:\0028\001*+\n\006Status\022\013\n" +
      "\007SUCCESS\020\000\022\n\n\006FAILED\020\001\022\010\n\004DEAD\020\0022\275\001\n\013Boo" +
      "kService\022(\n\tgetBooks1\022\014.BookRequest\032\r.Bo" +
      "okResponse\022*\n\tgetBooks2\022\014.BookRequest\032\r." +
      "BookResponse0\001\022*\n\tgetBooks3\022\014.BookReques" +
      "t\032\r.BookResponse(\001\022,\n\tgetBooks4\022\014.BookRe" +
      "quest\032\r.BookResponse(\0010\001B\031\n\025com.xiaomi.d" +
      "emo.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_Book_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Book_descriptor,
        new java.lang.String[] { "BookId", "BookName", });
    internal_static_BookRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookRequest_descriptor,
        new java.lang.String[] { "BookId", "BookName", "BookName", });
    internal_static_BookResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookResponse_descriptor,
        new java.lang.String[] { "Books", "Status", "BookMap", });
    internal_static_BookResponse_BookMapEntry_descriptor =
      internal_static_BookResponse_descriptor.getNestedTypes().get(0);
    internal_static_BookResponse_BookMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookResponse_BookMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
