// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Book.proto

package com.xiaomi.demo.rpc.proto;

/**
 * Protobuf type {@code BookRequest}
 */
public final class BookRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BookRequest)
    BookRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BookRequest.newBuilder() to construct.
  private BookRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BookRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BookRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BookRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            bookId_ = input.readInt64();
            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = bookName_.toBuilder();
            }
            bookName_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bookName_);
              bookName_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xiaomi.demo.rpc.proto.BookOuterClass.internal_static_BookRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xiaomi.demo.rpc.proto.BookOuterClass.internal_static_BookRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xiaomi.demo.rpc.proto.BookRequest.class, com.xiaomi.demo.rpc.proto.BookRequest.Builder.class);
  }

  private int bitField0_;
  public static final int BOOKID_FIELD_NUMBER = 1;
  private long bookId_;
  /**
   * <code>int64 bookId = 1;</code>
   * @return The bookId.
   */
  @java.lang.Override
  public long getBookId() {
    return bookId_;
  }

  public static final int BOOKNAME_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue bookName_;
  /**
   * <code>.google.protobuf.StringValue bookName = 2;</code>
   * @return Whether the bookName field is set.
   */
  @java.lang.Override
  public boolean hasBookName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.StringValue bookName = 2;</code>
   * @return The bookName.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getBookName() {
    return bookName_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : bookName_;
  }
  /**
   * <code>.google.protobuf.StringValue bookName = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getBookNameOrBuilder() {
    return bookName_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : bookName_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bookId_ != 0L) {
      output.writeInt64(1, bookId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getBookName());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bookId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, bookId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBookName());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xiaomi.demo.rpc.proto.BookRequest)) {
      return super.equals(obj);
    }
    com.xiaomi.demo.rpc.proto.BookRequest other = (com.xiaomi.demo.rpc.proto.BookRequest) obj;

    if (getBookId()
        != other.getBookId()) return false;
    if (hasBookName() != other.hasBookName()) return false;
    if (hasBookName()) {
      if (!getBookName()
          .equals(other.getBookName())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOOKID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBookId());
    if (hasBookName()) {
      hash = (37 * hash) + BOOKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getBookName().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xiaomi.demo.rpc.proto.BookRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xiaomi.demo.rpc.proto.BookRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xiaomi.demo.rpc.proto.BookRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xiaomi.demo.rpc.proto.BookRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xiaomi.demo.rpc.proto.BookRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xiaomi.demo.rpc.proto.BookRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xiaomi.demo.rpc.proto.BookRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xiaomi.demo.rpc.proto.BookRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xiaomi.demo.rpc.proto.BookRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xiaomi.demo.rpc.proto.BookRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xiaomi.demo.rpc.proto.BookRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xiaomi.demo.rpc.proto.BookRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xiaomi.demo.rpc.proto.BookRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BookRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BookRequest)
      com.xiaomi.demo.rpc.proto.BookRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiaomi.demo.rpc.proto.BookOuterClass.internal_static_BookRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiaomi.demo.rpc.proto.BookOuterClass.internal_static_BookRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiaomi.demo.rpc.proto.BookRequest.class, com.xiaomi.demo.rpc.proto.BookRequest.Builder.class);
    }

    // Construct using com.xiaomi.demo.proto.BookRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBookNameFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bookId_ = 0L;

      if (bookNameBuilder_ == null) {
        bookName_ = null;
      } else {
        bookNameBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xiaomi.demo.rpc.proto.BookOuterClass.internal_static_BookRequest_descriptor;
    }

    @java.lang.Override
    public com.xiaomi.demo.rpc.proto.BookRequest getDefaultInstanceForType() {
      return com.xiaomi.demo.rpc.proto.BookRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.xiaomi.demo.rpc.proto.BookRequest build() {
      com.xiaomi.demo.rpc.proto.BookRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xiaomi.demo.rpc.proto.BookRequest buildPartial() {
      com.xiaomi.demo.rpc.proto.BookRequest result = new com.xiaomi.demo.rpc.proto.BookRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.bookId_ = bookId_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (bookNameBuilder_ == null) {
          result.bookName_ = bookName_;
        } else {
          result.bookName_ = bookNameBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xiaomi.demo.rpc.proto.BookRequest) {
        return mergeFrom((com.xiaomi.demo.rpc.proto.BookRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xiaomi.demo.rpc.proto.BookRequest other) {
      if (other == com.xiaomi.demo.rpc.proto.BookRequest.getDefaultInstance()) return this;
      if (other.getBookId() != 0L) {
        setBookId(other.getBookId());
      }
      if (other.hasBookName()) {
        mergeBookName(other.getBookName());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xiaomi.demo.rpc.proto.BookRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xiaomi.demo.rpc.proto.BookRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long bookId_ ;
    /**
     * <code>int64 bookId = 1;</code>
     * @return The bookId.
     */
    @java.lang.Override
    public long getBookId() {
      return bookId_;
    }
    /**
     * <code>int64 bookId = 1;</code>
     * @param value The bookId to set.
     * @return This builder for chaining.
     */
    public Builder setBookId(long value) {
      
      bookId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bookId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBookId() {
      
      bookId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.StringValue bookName_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> bookNameBuilder_;
    /**
     * <code>.google.protobuf.StringValue bookName = 2;</code>
     * @return Whether the bookName field is set.
     */
    public boolean hasBookName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.StringValue bookName = 2;</code>
     * @return The bookName.
     */
    public com.google.protobuf.StringValue getBookName() {
      if (bookNameBuilder_ == null) {
        return bookName_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : bookName_;
      } else {
        return bookNameBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue bookName = 2;</code>
     */
    public Builder setBookName(com.google.protobuf.StringValue value) {
      if (bookNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bookName_ = value;
        onChanged();
      } else {
        bookNameBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue bookName = 2;</code>
     */
    public Builder setBookName(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (bookNameBuilder_ == null) {
        bookName_ = builderForValue.build();
        onChanged();
      } else {
        bookNameBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue bookName = 2;</code>
     */
    public Builder mergeBookName(com.google.protobuf.StringValue value) {
      if (bookNameBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            bookName_ != null &&
            bookName_ != com.google.protobuf.StringValue.getDefaultInstance()) {
          bookName_ =
            com.google.protobuf.StringValue.newBuilder(bookName_).mergeFrom(value).buildPartial();
        } else {
          bookName_ = value;
        }
        onChanged();
      } else {
        bookNameBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue bookName = 2;</code>
     */
    public Builder clearBookName() {
      if (bookNameBuilder_ == null) {
        bookName_ = null;
        onChanged();
      } else {
        bookNameBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue bookName = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getBookNameBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBookNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue bookName = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getBookNameOrBuilder() {
      if (bookNameBuilder_ != null) {
        return bookNameBuilder_.getMessageOrBuilder();
      } else {
        return bookName_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : bookName_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue bookName = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getBookNameFieldBuilder() {
      if (bookNameBuilder_ == null) {
        bookNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getBookName(),
                getParentForChildren(),
                isClean());
        bookName_ = null;
      }
      return bookNameBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BookRequest)
  }

  // @@protoc_insertion_point(class_scope:BookRequest)
  private static final com.xiaomi.demo.rpc.proto.BookRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xiaomi.demo.rpc.proto.BookRequest();
  }

  public static com.xiaomi.demo.rpc.proto.BookRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BookRequest>
      PARSER = new com.google.protobuf.AbstractParser<BookRequest>() {
    @java.lang.Override
    public BookRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BookRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BookRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BookRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xiaomi.demo.rpc.proto.BookRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

