#未配置资源配额：服务质量为 BestEffort，字面意思是“尽力而为”，它在服务质量中优先级
#最低，当产生驱逐行为时候，kubernetes 首先驱逐这一类型的 Pod。
#Request 小于 Limit：服务质量为 Burstable，字面意思是“突发”，优先级介于 BestEffort 和
#Guaranteed 之间。
#Request 等于 Limit：服务质量为 Guaranteed，字面意思是“保证”，优先级最高


apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: dev-ns

spec:
  limits:
    ## 内存的写法和磁盘容量一样，使用 Ki、Mi、Gi 来表示 KB、MB、GB，比如 512Ki、100Mi、0.5Gi 等。
    #而 CPU 因为在计算机中数量有限，非常宝贵，所以 Kubernetes 允许容器精细分割 CPU，即
    #可以 1 个、2 个地完整使用 CPU，也可以用小数 0.1、0.2 的方式来部分使用 CPU。这其实是
    #效仿了 UNIX“时间片”的用法，意思是进程最多可以占用多少 CPU 时间。
    #不过 CPU 时间也不能无限分割，Kubernetes 里 CPU 的最小使用单位是 0.001，为了方便表
    #示用了一个特别的单位 m，也就是“milli”“毫”的意思，比如说 500m 就相当于 0.5
    - type: Container
      defaultRequest:
        cpu: 200m
        memory: 50Mi
      default:
        cpu: 500m
        memory: 100Mi
    - type: Pod
      max:
        cpu: 800m
        memory: 200Mi