# kubectl create ns dev-ns $out
# kubectl create quota dev-qt $out
#
# kubectl explain quota.spec
# kubectl describe -n dev-ns quota dev-qt
#
# kubectl explain limits.spec.limits
#
# kubectl run ngx --image=nginx:alpine -n dev-ns
# kubectl describe pod ngx -n dev-ns
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-qt
  namespace: dev-ns

spec:
  hard:
    requests.cpu: "10"
    requests.memory: 10Gi
    limits.cpu: "10"
    limits.memory: 20Gi

    requests.storage: 100Gi
    persistentvolumeclaims: '100'

    pods: '100'
    configmaps: '100'
    secrets: '100'
    services: '10'
    services.nodeports: '5'
    count/jobs.batch: '1'
    count/cronjobs.batch: '1'
    count/deployments.apps: '1'


